language: node_js
node_js:
  - '13'

os:
  - linux

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GOOGLE_DOCKER_IMAGE=gcr.io/athenian-1/web-app
    - IMAGE_BRANCH_COMMIT=${GOOGLE_DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}

stages:
  - name: test
  - name: build
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request

jobs:
  fast_finish: true
  include:
    - stage: test
      name: 'Frontend Tests'
      script:
        - make test
    - stage: build
      name: 'Frontend Build'
      script:
        - make build
    - stage: deploy
      name: 'Deploy App'
      script:
        - |
          if [ ! -z "$TRAVIS_TAG" ]; then
            IMAGE=${GOOGLE_DOCKER_IMAGE}:${TRAVIS_TAG} make docker-build gcloud-login docker-push
            exit 0
          fi
        - IMAGE=${IMAGE_BRANCH_COMMIT} make deploy
        - docker tag ${IMAGE_BRANCH_COMMIT} ${GOOGLE_DOCKER_IMAGE}:latest
        - IMAGE=${GOOGLE_DOCKER_IMAGE}:latest make docker-push
