language: install
node_js:
  - node

os:
  - linux

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GOOGLE_DOCKER_IMAGE=gcr.io/athenian-1/web-app
    - IMAGE_BRANCH_COMMIT=${GOOGLE_DOCKER_IMAGE}:${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}

stages:
  - name: test
  - name: build
  - name: deploy
    if: branch IN (master, production) AND type != pull_request

jobs:
  fast_finish: true
  include:
    - stage: build
      name: 'Frontend Build'
      script:
        - make dependencies
        - make build
    - stage: deploy
      name: 'Deploy App'
      script:
        - IMAGE=${IMAGE_BRANCH_COMMIT} make deploy
        - docker tag ${IMAGE_BRANCH_COMMIT} ${GOOGLE_DOCKER_IMAGE}:latest
        - IMAGE=${GOOGLE_DOCKER_IMAGE}:latest make docker-push
