# Package configuration
PROJECT = athenian-webapp
SERVICE_NAME = web-app

CI_REPOSITORY ?= https://github.com/athenianco/ci
CI_BRANCH ?= master
CI_PATH ?= .ci
MAKEFILE := $(CI_PATH)/Makefile.main
$(MAKEFILE):
	git clone --quiet --depth 1 -b $(CI_BRANCH) $(CI_REPOSITORY) $(CI_PATH);
-include $(MAKEFILE)

# If CI flags is set, build will fail if there are any WARNING log, and tests will run and exit instead of watching for changes.
# CI is set to '1' in travis by default
CI ?=

# TODO (dpordomingo): consider locking to fixed version once we start doing releases.
API_SPECS_URL ?= https://raw.githubusercontent.com/athenianco/athenian-api/master/server/athenian/api/openapi/openapi.yaml

API_SERVICE_PATH := src/js/services/api
API_CLIENT_CODE_PATH := $(API_SERVICE_PATH)/openapi-client

OPENAPI_GENERATOR := node_modules/@openapitools/openapi-generator-cli/bin/openapi-generator

.PHONY: api-generate
api-generate: $(OPENAPI_GENERATOR) clean-openapi
	node_modules/@openapitools/openapi-generator-cli/bin/openapi-generator generate \
		--input-spec=$(API_SPECS_URL) \
		--output=$(API_CLIENT_CODE_PATH) \
		--generator-name=javascript \
		--ignore-file-override=$(API_SERVICE_PATH)/.openapi-generator-ignore \
		--config=$(API_SERVICE_PATH)/.openapi-config.yml \
		-DmodelTests=false,modelDocs=false,apiTests=false,apiDocs=false;

.PHONY: clean
clean: clean-openapi

.PHONY: clean-openapi
clean-openapi:
	rm -rf $(API_CLIENT_CODE_PATH)

.PHONY: build
build:
	# The API client, as generated by OpenAPI does not compile with CI=1 because it logs some WARNINGS.
	# This is also the create-react-app recommended way to proceed when building under these situations.
	# see https://github.com/facebook/create-react-app/issues/2453#issuecomment-306886060
	CI=false yarn build

.PHONY: serve
serve:
	yarn install
	yarn start

.PHONY: test
test:
	yarn test

.PHONY: generate
generate: api-generate

.PHONY: dependencies
dependencies: app-dependencies

.PHONY: app-dependencies
app-dependencies:
	yarn install

$(OPENAPI_GENERATOR): app-dependencies
