/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountUserChangeRequest model module.
 * @module model/AccountUserChangeRequest
 * @version 1.0.32
 */
class AccountUserChangeRequest {
    /**
     * Constructs a new <code>AccountUserChangeRequest</code>.
     * Request to change an account member&#39;s status.
     * @alias module:model/AccountUserChangeRequest
     * @param account {Number} Account ID.
     * @param user {String} Account member ID.
     * @param status {module:model/AccountUserChangeRequest.StatusEnum} Account membership role.
     */
    constructor(account, user, status) { 
        
        AccountUserChangeRequest.initialize(this, account, user, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, account, user, status) { 
        obj['account'] = account;
        obj['user'] = user;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>AccountUserChangeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountUserChangeRequest} obj Optional instance to populate.
     * @return {module:model/AccountUserChangeRequest} The populated <code>AccountUserChangeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountUserChangeRequest();

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Account ID.
 * @member {Number} account
 */
AccountUserChangeRequest.prototype['account'] = undefined;

/**
 * Account member ID.
 * @member {String} user
 */
AccountUserChangeRequest.prototype['user'] = undefined;

/**
 * Account membership role.
 * @member {module:model/AccountUserChangeRequest.StatusEnum} status
 */
AccountUserChangeRequest.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
AccountUserChangeRequest['StatusEnum'] = {

    /**
     * value: "regular"
     * @const
     */
    "regular": "regular",

    /**
     * value: "admin"
     * @const
     */
    "admin": "admin",

    /**
     * value: "banished"
     * @const
     */
    "banished": "banished"
};



export default AccountUserChangeRequest;

