/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CalculatedMetric from './CalculatedMetric';
import MetricID from './MetricID';

/**
 * The CalculatedMetrics model module.
 * @module model/CalculatedMetrics
 * @version 1.0.4
 */
class CalculatedMetrics {
    /**
     * Constructs a new <code>CalculatedMetrics</code>.
     * @alias module:model/CalculatedMetrics
     * @param calculated {Array.<module:model/CalculatedMetric>} Values of the requested metrics through time. The sequence order is not guaranteed to be the same as in the preceding request.
     * @param metrics {Array.<module:model/MetricID>} Repeats `PullRequestMetricsRequest.metrics`.
     * @param dateFrom {Date} Repeats `PullRequestMetricsRequest.date_from`.
     * @param dateTo {Date} Repeats `PullRequestMetricsRequest.date_to`.
     * @param granularity {String} How often the metrics are reported. The value must satisfy the following regular expression: (^([1-9]\\d* )?(day|week|month|year)$
     */
    constructor(calculated, metrics, dateFrom, dateTo, granularity) { 
        
        CalculatedMetrics.initialize(this, calculated, metrics, dateFrom, dateTo, granularity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, calculated, metrics, dateFrom, dateTo, granularity) { 
        obj['calculated'] = calculated;
        obj['metrics'] = metrics;
        obj['date_from'] = dateFrom;
        obj['date_to'] = dateTo;
        obj['granularity'] = granularity;
    }

    /**
     * Constructs a <code>CalculatedMetrics</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CalculatedMetrics} obj Optional instance to populate.
     * @return {module:model/CalculatedMetrics} The populated <code>CalculatedMetrics</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CalculatedMetrics();

            if (data.hasOwnProperty('calculated')) {
                obj['calculated'] = ApiClient.convertToType(data['calculated'], [CalculatedMetric]);
            }
            if (data.hasOwnProperty('metrics')) {
                obj['metrics'] = ApiClient.convertToType(data['metrics'], [MetricID]);
            }
            if (data.hasOwnProperty('date_from')) {
                obj['date_from'] = ApiClient.convertToType(data['date_from'], 'Date');
            }
            if (data.hasOwnProperty('date_to')) {
                obj['date_to'] = ApiClient.convertToType(data['date_to'], 'Date');
            }
            if (data.hasOwnProperty('granularity')) {
                obj['granularity'] = ApiClient.convertToType(data['granularity'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Values of the requested metrics through time. The sequence order is not guaranteed to be the same as in the preceding request.
 * @member {Array.<module:model/CalculatedMetric>} calculated
 */
CalculatedMetrics.prototype['calculated'] = undefined;

/**
 * Repeats `PullRequestMetricsRequest.metrics`.
 * @member {Array.<module:model/MetricID>} metrics
 */
CalculatedMetrics.prototype['metrics'] = undefined;

/**
 * Repeats `PullRequestMetricsRequest.date_from`.
 * @member {Date} date_from
 */
CalculatedMetrics.prototype['date_from'] = undefined;

/**
 * Repeats `PullRequestMetricsRequest.date_to`.
 * @member {Date} date_to
 */
CalculatedMetrics.prototype['date_to'] = undefined;

/**
 * How often the metrics are reported. The value must satisfy the following regular expression: (^([1-9]\\d* )?(day|week|month|year)$
 * @member {String} granularity
 */
CalculatedMetrics.prototype['granularity'] = undefined;






export default CalculatedMetrics;

