/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Commit from './Commit';

/**
 * The CommitGroupForFilterCommitsRequest model module.
 * @module model/CommitGroupForFilterCommitsRequest
 * @version 1.0.5
 */
class CommitGroupForFilterCommitsRequest {
    /**
     * Constructs a new <code>CommitGroupForFilterCommitsRequest</code>.
     * List of commits that were committed starting from a specific time and ending at +granularity.
     * @alias module:model/CommitGroupForFilterCommitsRequest
     * @param _date {Date} Commits were pushed beginning with this date. They were not pushed later than +granularity.
     * @param commits {Array.<module:model/Commit>} 
     */
    constructor(_date, commits) { 
        
        CommitGroupForFilterCommitsRequest.initialize(this, _date, commits);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _date, commits) { 
        obj['date'] = _date;
        obj['commits'] = commits;
    }

    /**
     * Constructs a <code>CommitGroupForFilterCommitsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CommitGroupForFilterCommitsRequest} obj Optional instance to populate.
     * @return {module:model/CommitGroupForFilterCommitsRequest} The populated <code>CommitGroupForFilterCommitsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommitGroupForFilterCommitsRequest();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('commits')) {
                obj['commits'] = ApiClient.convertToType(data['commits'], [Commit]);
            }
        }
        return obj;
    }


}

/**
 * Commits were pushed beginning with this date. They were not pushed later than +granularity.
 * @member {Date} date
 */
CommitGroupForFilterCommitsRequest.prototype['date'] = undefined;

/**
 * @member {Array.<module:model/Commit>} commits
 */
CommitGroupForFilterCommitsRequest.prototype['commits'] = undefined;






export default CommitGroupForFilterCommitsRequest;

