/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.27
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DeveloperMetricID.
* @enum {}
* @readonly
*/
export default class DeveloperMetricID {
    
        /**
         * value: "dev-commits-pushed"
         * @const
         */
        "commits-pushed" = "dev-commits-pushed";

    
        /**
         * value: "dev-lines-changed"
         * @const
         */
        "lines-changed" = "dev-lines-changed";

    
        /**
         * value: "dev-prs-created"
         * @const
         */
        "prs-created" = "dev-prs-created";

    
        /**
         * value: "dev-prs-merged"
         * @const
         */
        "prs-merged" = "dev-prs-merged";

    
        /**
         * value: "dev-releases"
         * @const
         */
        "releases" = "dev-releases";

    
        /**
         * value: "dev-reviews"
         * @const
         */
        "reviews" = "dev-reviews";

    
        /**
         * value: "dev-review-approvals"
         * @const
         */
        "review-approvals" = "dev-review-approvals";

    
        /**
         * value: "dev-review-rejections"
         * @const
         */
        "review-rejections" = "dev-review-rejections";

    
        /**
         * value: "dev-review-neutrals"
         * @const
         */
        "review-neutrals" = "dev-review-neutrals";

    
        /**
         * value: "dev-pr-comments"
         * @const
         */
        "pr-comments" = "dev-pr-comments";

    
        /**
         * value: "dev-regular-pr-comments"
         * @const
         */
        "regular-pr-comments" = "dev-regular-pr-comments";

    
        /**
         * value: "dev-review-pr-comments"
         * @const
         */
        "review-pr-comments" = "dev-review-pr-comments";

    

    /**
    * Returns a <code>DeveloperMetricID</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DeveloperMetricID} The enum <code>DeveloperMetricID</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

