/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.41
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeveloperMetricID from './DeveloperMetricID';
import ForSet from './ForSet';

/**
 * The DeveloperMetricsRequest model module.
 * @module model/DeveloperMetricsRequest
 * @version 1.0.41
 */
class DeveloperMetricsRequest {
    /**
     * Constructs a new <code>DeveloperMetricsRequest</code>.
     * Request for calculating metrics on top of developer activities.
     * @alias module:model/DeveloperMetricsRequest
     * @param _for {Array.<module:model/ForSet>} Sets of developers and repositories to calculate the metrics for.
     * @param metrics {Array.<module:model/DeveloperMetricID>} Requested metric identifiers.
     * @param dateFrom {Date} Date from when to start measuring the metrics.
     * @param dateTo {Date} Date up to which to measure the metrics.
     * @param account {Number} Session account ID.
     */
    constructor(_for, metrics, dateFrom, dateTo, account) { 
        
        DeveloperMetricsRequest.initialize(this, _for, metrics, dateFrom, dateTo, account);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _for, metrics, dateFrom, dateTo, account) { 
        obj['for'] = _for;
        obj['metrics'] = metrics;
        obj['date_from'] = dateFrom;
        obj['date_to'] = dateTo;
        obj['account'] = account;
    }

    /**
     * Constructs a <code>DeveloperMetricsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeveloperMetricsRequest} obj Optional instance to populate.
     * @return {module:model/DeveloperMetricsRequest} The populated <code>DeveloperMetricsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeveloperMetricsRequest();

            if (data.hasOwnProperty('for')) {
                obj['for'] = ApiClient.convertToType(data['for'], [ForSet]);
            }
            if (data.hasOwnProperty('metrics')) {
                obj['metrics'] = ApiClient.convertToType(data['metrics'], [DeveloperMetricID]);
            }
            if (data.hasOwnProperty('date_from')) {
                obj['date_from'] = ApiClient.convertToType(data['date_from'], 'Date');
            }
            if (data.hasOwnProperty('date_to')) {
                obj['date_to'] = ApiClient.convertToType(data['date_to'], 'Date');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'Number');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Sets of developers and repositories to calculate the metrics for.
 * @member {Array.<module:model/ForSet>} for
 */
DeveloperMetricsRequest.prototype['for'] = undefined;

/**
 * Requested metric identifiers.
 * @member {Array.<module:model/DeveloperMetricID>} metrics
 */
DeveloperMetricsRequest.prototype['metrics'] = undefined;

/**
 * Date from when to start measuring the metrics.
 * @member {Date} date_from
 */
DeveloperMetricsRequest.prototype['date_from'] = undefined;

/**
 * Date up to which to measure the metrics.
 * @member {Date} date_to
 */
DeveloperMetricsRequest.prototype['date_to'] = undefined;

/**
 * Local time zone offset in minutes, used to adjust `date_from` and `date_to`.
 * @member {Number} timezone
 */
DeveloperMetricsRequest.prototype['timezone'] = undefined;

/**
 * Session account ID.
 * @member {Number} account
 */
DeveloperMetricsRequest.prototype['account'] = undefined;






export default DeveloperMetricsRequest;

