/**
 * Athenian Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FilterItemsRequest model module.
 * @module model/FilterItemsRequest
 * @version 1.0.0
 */
class FilterItemsRequest {
    /**
     * Constructs a new <code>FilterItemsRequest</code>.
     * @alias module:model/FilterItemsRequest
     * @param account {Number} Session account ID.
     * @param dateFrom {Date} Updates must be later than or equal to this date.
     * @param dateTo {Date} Updates must be earlier than or equal to this date.
     */
    constructor(account, dateFrom, dateTo) { 
        
        FilterItemsRequest.initialize(this, account, dateFrom, dateTo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, account, dateFrom, dateTo) { 
        obj['account'] = account;
        obj['date_from'] = dateFrom;
        obj['date_to'] = dateTo;
    }

    /**
     * Constructs a <code>FilterItemsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FilterItemsRequest} obj Optional instance to populate.
     * @return {module:model/FilterItemsRequest} The populated <code>FilterItemsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FilterItemsRequest();

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'Number');
            }
            if (data.hasOwnProperty('date_from')) {
                obj['date_from'] = ApiClient.convertToType(data['date_from'], 'Date');
            }
            if (data.hasOwnProperty('date_to')) {
                obj['date_to'] = ApiClient.convertToType(data['date_to'], 'Date');
            }
            if (data.hasOwnProperty('in')) {
                obj['in'] = ApiClient.convertToType(data['in'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Session account ID.
 * @member {Number} account
 */
FilterItemsRequest.prototype['account'] = undefined;

/**
 * Updates must be later than or equal to this date.
 * @member {Date} date_from
 */
FilterItemsRequest.prototype['date_from'] = undefined;

/**
 * Updates must be earlier than or equal to this date.
 * @member {Date} date_to
 */
FilterItemsRequest.prototype['date_to'] = undefined;

/**
 * A set of repositories. An empty list results an empty response in contrary to DeveloperSet. Duplicates are automatically ignored.
 * @member {Array.<String>} in
 */
FilterItemsRequest.prototype['in'] = undefined;






export default FilterItemsRequest;

