/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IncludedNativeUser from './IncludedNativeUser';

/**
 * The IncludedNativeUsers model module.
 * @module model/IncludedNativeUsers
 * @version 1.0.5
 */
class IncludedNativeUsers {
    /**
     * Constructs a new <code>IncludedNativeUsers</code>.
     * @alias module:model/IncludedNativeUsers
     * @param users {Object.<String, module:model/IncludedNativeUser>} Mapping user native (e.g., GitHub) login ID -> user details. The users are mentioned in the PRs from \"PullRequestSet.data\" or in the commits from \"FilterCommitsRequest.data\".
     */
    constructor(users) { 
        
        IncludedNativeUsers.initialize(this, users);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, users) { 
        obj['users'] = users;
    }

    /**
     * Constructs a <code>IncludedNativeUsers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IncludedNativeUsers} obj Optional instance to populate.
     * @return {module:model/IncludedNativeUsers} The populated <code>IncludedNativeUsers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IncludedNativeUsers();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], {'String': IncludedNativeUser});
            }
        }
        return obj;
    }


}

/**
 * Mapping user native (e.g., GitHub) login ID -> user details. The users are mentioned in the PRs from \"PullRequestSet.data\" or in the commits from \"FilterCommitsRequest.data\".
 * @member {Object.<String, module:model/IncludedNativeUser>} users
 */
IncludedNativeUsers.prototype['users'] = undefined;






export default IncludedNativeUsers;

