/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.49
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GenericError from './GenericError';
import InvalidRequestErrorAllOf from './InvalidRequestErrorAllOf';

/**
 * The InvalidRequestError model module.
 * @module model/InvalidRequestError
 * @version 1.0.49
 */
class InvalidRequestError {
    /**
     * Constructs a new <code>InvalidRequestError</code>.
     * @alias module:model/InvalidRequestError
     * @implements module:model/GenericError
     * @implements module:model/InvalidRequestErrorAllOf
     * @param type {String} URI reference that identifies the problem type (RFC 7807).
     * @param title {String} Short, human-readable summary of the problem type.
     */
    constructor(type, title) { 
        GenericError.initialize(this, type, title);InvalidRequestErrorAllOf.initialize(this);
        InvalidRequestError.initialize(this, type, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, title) { 
        obj['type'] = type;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>InvalidRequestError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvalidRequestError} obj Optional instance to populate.
     * @return {module:model/InvalidRequestError} The populated <code>InvalidRequestError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvalidRequestError();
            GenericError.constructFromObject(data, obj);
            InvalidRequestErrorAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], 'String');
            }
            if (data.hasOwnProperty('instance')) {
                obj['instance'] = ApiClient.convertToType(data['instance'], 'String');
            }
            if (data.hasOwnProperty('pointer')) {
                obj['pointer'] = ApiClient.convertToType(data['pointer'], 'String');
            }
        }
        return obj;
    }


}

/**
 * URI reference that identifies the problem type (RFC 7807).
 * @member {String} type
 */
InvalidRequestError.prototype['type'] = undefined;

/**
 * Short, human-readable summary of the problem type.
 * @member {String} title
 */
InvalidRequestError.prototype['title'] = undefined;

/**
 * Duplicated HTTP status code.
 * @member {Number} status
 */
InvalidRequestError.prototype['status'] = undefined;

/**
 * Human-readable explanation specific to this occurrence of the problem.
 * @member {String} detail
 */
InvalidRequestError.prototype['detail'] = undefined;

/**
 * URI reference that identifies the specific occurrence of the problem.
 * @member {String} instance
 */
InvalidRequestError.prototype['instance'] = undefined;

/**
 * Path to the offending request item.
 * @member {String} pointer
 */
InvalidRequestError.prototype['pointer'] = undefined;


// Implement GenericError interface:
/**
 * URI reference that identifies the problem type (RFC 7807).
 * @member {String} type
 */
GenericError.prototype['type'] = undefined;
/**
 * Short, human-readable summary of the problem type.
 * @member {String} title
 */
GenericError.prototype['title'] = undefined;
/**
 * Duplicated HTTP status code.
 * @member {Number} status
 */
GenericError.prototype['status'] = undefined;
/**
 * Human-readable explanation specific to this occurrence of the problem.
 * @member {String} detail
 */
GenericError.prototype['detail'] = undefined;
/**
 * URI reference that identifies the specific occurrence of the problem.
 * @member {String} instance
 */
GenericError.prototype['instance'] = undefined;
// Implement InvalidRequestErrorAllOf interface:
/**
 * Path to the offending request item.
 * @member {String} pointer
 */
InvalidRequestErrorAllOf.prototype['pointer'] = undefined;




export default InvalidRequestError;

