/**
 * Athenian Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ForSet from './ForSet';
import Granularity from './Granularity';
import MetricID from './MetricID';

/**
 * The MetricsRequest model module.
 * @module model/MetricsRequest
 * @version 1.0.0
 */
class MetricsRequest {
    /**
     * Constructs a new <code>MetricsRequest</code>.
     * @alias module:model/MetricsRequest
     * @param _for {Array.<module:model/ForSet>} Sets of developers and repositories to calculate the metrics for.
     * @param metrics {Array.<module:model/MetricID>} Requested metric identifiers.
     * @param dateFrom {Date} The date from when to start measuring the metrics.
     * @param dateTo {Date} The date up to which to measure the metrics.
     * @param granularity {module:model/Granularity} 
     * @param account {Number} User's account ID.
     */
    constructor(_for, metrics, dateFrom, dateTo, granularity, account) { 
        
        MetricsRequest.initialize(this, _for, metrics, dateFrom, dateTo, granularity, account);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _for, metrics, dateFrom, dateTo, granularity, account) { 
        obj['for'] = _for;
        obj['metrics'] = metrics;
        obj['date_from'] = dateFrom;
        obj['date_to'] = dateTo;
        obj['granularity'] = granularity;
        obj['account'] = account;
    }

    /**
     * Constructs a <code>MetricsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetricsRequest} obj Optional instance to populate.
     * @return {module:model/MetricsRequest} The populated <code>MetricsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetricsRequest();

            if (data.hasOwnProperty('for')) {
                obj['for'] = ApiClient.convertToType(data['for'], [ForSet]);
            }
            if (data.hasOwnProperty('metrics')) {
                obj['metrics'] = ApiClient.convertToType(data['metrics'], [MetricID]);
            }
            if (data.hasOwnProperty('date_from')) {
                obj['date_from'] = ApiClient.convertToType(data['date_from'], 'Date');
            }
            if (data.hasOwnProperty('date_to')) {
                obj['date_to'] = ApiClient.convertToType(data['date_to'], 'Date');
            }
            if (data.hasOwnProperty('granularity')) {
                obj['granularity'] = Granularity.constructFromObject(data['granularity']);
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Sets of developers and repositories to calculate the metrics for.
 * @member {Array.<module:model/ForSet>} for
 */
MetricsRequest.prototype['for'] = undefined;

/**
 * Requested metric identifiers.
 * @member {Array.<module:model/MetricID>} metrics
 */
MetricsRequest.prototype['metrics'] = undefined;

/**
 * The date from when to start measuring the metrics.
 * @member {Date} date_from
 */
MetricsRequest.prototype['date_from'] = undefined;

/**
 * The date up to which to measure the metrics.
 * @member {Date} date_to
 */
MetricsRequest.prototype['date_to'] = undefined;

/**
 * @member {module:model/Granularity} granularity
 */
MetricsRequest.prototype['granularity'] = undefined;

/**
 * User's account ID.
 * @member {Number} account
 */
MetricsRequest.prototype['account'] = undefined;






export default MetricsRequest;

