/**
 * Athenian Dashboard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MetricID.
* @enum {}
* @readonly
*/
export default class MetricID {
    
        /**
         * value: "pr-wip-time"
         * @const
         */
        "wip-time" = "pr-wip-time";

    
        /**
         * value: "pr-review-time"
         * @const
         */
        "review-time" = "pr-review-time";

    
        /**
         * value: "pr-merging-time"
         * @const
         */
        "merging-time" = "pr-merging-time";

    
        /**
         * value: "pr-release-time"
         * @const
         */
        "release-time" = "pr-release-time";

    
        /**
         * value: "pr-lead-time"
         * @const
         */
        "lead-time" = "pr-lead-time";

    

    /**
    * Returns a <code>MetricID</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MetricID} The enum <code>MetricID</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

