/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ {{ commit }}
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MetricID.
* @enum {}
* @readonly
*/
export default class MetricID {
    
        /**
         * value: "pr-wip-time"
         * @const
         */
        "wip-time" = "pr-wip-time";

    
        /**
         * value: "pr-review-time"
         * @const
         */
        "review-time" = "pr-review-time";

    
        /**
         * value: "pr-merging-time"
         * @const
         */
        "merging-time" = "pr-merging-time";

    
        /**
         * value: "pr-release-time"
         * @const
         */
        "release-time" = "pr-release-time";

    
        /**
         * value: "pr-lead-time"
         * @const
         */
        "lead-time" = "pr-lead-time";

    
        /**
         * value: "pr-flow-ratio"
         * @const
         */
        "flow-ratio" = "pr-flow-ratio";

    
        /**
         * value: "pr-opened"
         * @const
         */
        "opened" = "pr-opened";

    
        /**
         * value: "pr-merged"
         * @const
         */
        "merged" = "pr-merged";

    
        /**
         * value: "pr-closed"
         * @const
         */
        "closed" = "pr-closed";

    
        /**
         * value: "pr-wait-first-review"
         * @const
         */
        "wait-first-review" = "pr-wait-first-review";

    

    /**
    * Returns a <code>MetricID</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MetricID} The enum <code>MetricID</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

