/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PullRequestMetricID.
* @enum {}
* @readonly
*/
export default class PullRequestMetricID {
    
        /**
         * value: "pr-wip-time"
         * @const
         */
        "wip-time" = "pr-wip-time";

    
        /**
         * value: "pr-wip-count"
         * @const
         */
        "wip-count" = "pr-wip-count";

    
        /**
         * value: "pr-review-time"
         * @const
         */
        "review-time" = "pr-review-time";

    
        /**
         * value: "pr-review-count"
         * @const
         */
        "review-count" = "pr-review-count";

    
        /**
         * value: "pr-merging-time"
         * @const
         */
        "merging-time" = "pr-merging-time";

    
        /**
         * value: "pr-merging-count"
         * @const
         */
        "merging-count" = "pr-merging-count";

    
        /**
         * value: "pr-release-time"
         * @const
         */
        "release-time" = "pr-release-time";

    
        /**
         * value: "pr-release-count"
         * @const
         */
        "release-count" = "pr-release-count";

    
        /**
         * value: "pr-lead-time"
         * @const
         */
        "lead-time" = "pr-lead-time";

    
        /**
         * value: "pr-lead-count"
         * @const
         */
        "lead-count" = "pr-lead-count";

    
        /**
         * value: "pr-cycle-time"
         * @const
         */
        "cycle-time" = "pr-cycle-time";

    
        /**
         * value: "pr-cycle-count"
         * @const
         */
        "cycle-count" = "pr-cycle-count";

    
        /**
         * value: "pr-all-count"
         * @const
         */
        "all-count" = "pr-all-count";

    
        /**
         * value: "pr-wait-first-review"
         * @const
         */
        "wait-first-review" = "pr-wait-first-review";

    
        /**
         * value: "pr-wait-first-review-count"
         * @const
         */
        "wait-first-review-count" = "pr-wait-first-review-count";

    
        /**
         * value: "pr-flow-ratio"
         * @const
         */
        "flow-ratio" = "pr-flow-ratio";

    
        /**
         * value: "pr-opened"
         * @const
         */
        "opened" = "pr-opened";

    
        /**
         * value: "pr-merged"
         * @const
         */
        "merged" = "pr-merged";

    
        /**
         * value: "pr-closed"
         * @const
         */
        "closed" = "pr-closed";

    
        /**
         * value: "pr-released"
         * @const
         */
        "released" = "pr-released";

    

    /**
    * Returns a <code>PullRequestMetricID</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PullRequestMetricID} The enum <code>PullRequestMetricID</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

