/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ {{ commit }}
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PullRequestPipelineStage.
* @enum {}
* @readonly
*/
export default class PullRequestPipelineStage {
    
        /**
         * value: "wip"
         * @const
         */
        "wip" = "wip";

    
        /**
         * value: "review"
         * @const
         */
        "review" = "review";

    
        /**
         * value: "merge"
         * @const
         */
        "merge" = "merge";

    
        /**
         * value: "release"
         * @const
         */
        "release" = "release";

    
        /**
         * value: "done"
         * @const
         */
        "done" = "done";

    

    /**
    * Returns a <code>PullRequestPipelineStage</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PullRequestPipelineStage} The enum <code>PullRequestPipelineStage</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

