/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StageTimings model module.
 * @module model/StageTimings
 * @version 1.0.48
 */
class StageTimings {
    /**
     * Constructs a new <code>StageTimings</code>.
     * Time spent by the PR in each pipeline stage.
     * @alias module:model/StageTimings
     */
    constructor() { 
        
        StageTimings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StageTimings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StageTimings} obj Optional instance to populate.
     * @return {module:model/StageTimings} The populated <code>StageTimings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StageTimings();

            if (data.hasOwnProperty('wip')) {
                obj['wip'] = ApiClient.convertToType(data['wip'], 'String');
            }
            if (data.hasOwnProperty('review')) {
                obj['review'] = ApiClient.convertToType(data['review'], 'String');
            }
            if (data.hasOwnProperty('merge')) {
                obj['merge'] = ApiClient.convertToType(data['merge'], 'String');
            }
            if (data.hasOwnProperty('release')) {
                obj['release'] = ApiClient.convertToType(data['release'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} wip
 */
StageTimings.prototype['wip'] = undefined;

/**
 * @member {String} review
 */
StageTimings.prototype['review'] = undefined;

/**
 * @member {String} merge
 */
StageTimings.prototype['merge'] = undefined;

/**
 * @member {String} release
 */
StageTimings.prototype['release'] = undefined;






export default StageTimings;

