/**
 * {{ title }}
 * Server version: {{ server_version }} built on {{ build_date }} @ [{{ commit }}](https://github.com/athenianco/athenian-api/commit/{{ commit }})
 *
 * The version of the OpenAPI document: 1.0.47
 * Contact: admin@athenian.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Versions model module.
 * @module model/Versions
 * @version 1.0.47
 */
class Versions {
    /**
     * Constructs a new <code>Versions</code>.
     * @alias module:model/Versions
     * @param api {String} 
     */
    constructor(api) { 
        
        Versions.initialize(this, api);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, api) { 
        obj['api'] = api;
    }

    /**
     * Constructs a <code>Versions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Versions} obj Optional instance to populate.
     * @return {module:model/Versions} The populated <code>Versions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Versions();

            if (data.hasOwnProperty('api')) {
                obj['api'] = ApiClient.convertToType(data['api'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} api
 */
Versions.prototype['api'] = undefined;






export default Versions;

